media:
  input: .
  output: /

content:
  - name: blog
    label: Blog
    type: collection
    path: blog
    format: raw
    filename: "{slug}.html"
    fields:
      - { name: title, type: string, required: true }
      - { name: body, type: rich-text }
